version: '3.3'

services:
  core:
    build:
      args:
        ENERGI_BIN: /usr/local/bin/energi
        ENERGI_CORE_DIR: /home/nrgstaker/.energi_core
        ENERGI_VERSION: v3.1.3
        STAKER_HOME: /home/nrgstaker/
      context: .
    image: energi3
    ports:
      - 39797:39797/tcp
      - 39797:39797/udp
    restart: unless-stopped
    volumes:
      - target: /home/nrgstaker/.energi_core
        type: volume
        source: core-data

volumes:
  core-data: